version: "3.8"

services:
  jenkins_agent:
    image: agent1-image:v1
    build:
      context: .
      dockerfile: DockerfileAgent1
    privileged: true
    user: root
    container_name: agent1
    ports:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY
    secrets:
      - host_ssh_key
    networks:
      mynetwork:
        ipv4_address: 192.168.1.200
  jenkins_agent_2:
    image: agent2-image:v1
    build:
      context: .
      dockerfile: DockerfileAgent2
    privileged: true
    user: root
    container_name: agent2
    ports:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY
    secrets:
      - host_ssh_key
    networks:
      mynetwork:
        ipv4_address: 192.168.1.201


secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa.pub

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.200/28